import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsString, IsInt, IsArray, ValidateNested, IsOptional } from 'class-validator';
import { SearchResultDto } from './search-result.dto';
import { WarningDto } from './warning.dto';

export class SearchResponseDto {
  @ApiProperty({
    description: 'Original query string',
    example: 'machine learning',
  })
  @IsString()
  query: string;

  @ApiProperty({
    description: 'Total number of aggregated search results matching criteria',
    example: 42,
  })
  @IsInt()
  total: number;

  @ApiProperty({
    description: 'Current page number',
    example: 1,
  })
  @IsInt()
  page: number;

  @ApiProperty({
    description: 'Limit per page',
    example: 10,
  })
  @IsInt()
  limit: number;

  @ApiProperty({
    description: 'List of aggregated normalized search results',
    type: [SearchResultDto],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SearchResultDto)
  results: SearchResultDto[];

  @ApiPropertyOptional({
    description: 'List of warnings generated by connector failures or missing API keys',
    type: [WarningDto],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => WarningDto)
  @IsOptional()
  warnings?: WarningDto[];
}
